### ISSUE TITLE
Fehlermeldung ino

### ISSUE THREAD

**Issue by vdagamb** [mdorenkamp/fhemduino#37]
Was muss ich anders machen?? 
pi@raspberrypi1 ~/fhemduino $ ino build -m nano328
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 76, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 282, in run
    self.setup_flags(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 154, in setup_flags
    '-DARDUINO=' + str(self.e.arduino_lib_version.as_int()),
  File "/usr/local/lib/python2.7/dist-packages/ino/environment.py", line 61, in as_int
    return self.major * 100 + self.minor * 10 + self.build
IndexError: tuple index out of range

**Comment by mdorenkamp** [comment]
hast du es mal mit einem sauberen ino projekt versucht? das sieht mir stark nach alten cache-files aus
